@startuml
'https://plantuml.com/class-diagram

abstract class Product{
  + void use()
}
abstract class Factory{
  + Product factoryMethod()
}
class ConcreteProduct{
  + void use()
}
class ConcreteFactory{
+ Product factoryMethod()
}
note right :return new ConcreteProduct();
Product <|.. ConcreteProduct
Factory <|.. ConcreteFactory

ConcreteProduct <..ConcreteFactory

@enduml